#ifndef DEVICE_CORE_SHARED_CONTEXT_HPP
#define DEVICE_CORE_SHARED_CONTEXT_HPP

#include <cstdint>
#include "spsc_queue.hpp"
#include "raw_sample.hpp"

namespace core {

// FIFO commands from Core 0 to Core 1
enum class FifoCmd : uint32_t {
    kNone        = 0,
    kStartStream = 1,  // Start sampling with current shared config
    kStopStream  = 2,  // Stop sampling
};

// Shared context between Core 0 and Core 1
// Placed in shared RAM, accessed by both cores
struct SharedContext {
    // === Written by Core 0, Read by Core 1 ===
    volatile uint16_t stream_period_us;   // Sampling period in microseconds
    volatile uint16_t stream_mask;        // Channel mask (which sensors to read)
    volatile uint32_t stream_start_us;    // Timestamp origin for relative timestamps

    // === Written by Core 1, Read by Core 0 ===
    volatile uint32_t samples_produced;   // Total samples generated by Core 1
    volatile uint32_t samples_dropped;    // Queue overflow count
    volatile bool i2c_error;              // Last I2C operation failed

    // === Sample Queue (SPSC) ===
    // Core 1 pushes, Core 0 pops
    SpscQueue<RawSample, 256> sample_queue;

    // Initialize to default values
    void init() {
        stream_period_us = 1000;  // 1kHz default
        stream_mask = 0x000F;     // All channels
        stream_start_us = 0;
        samples_produced = 0;
        samples_dropped = 0;
        i2c_error = false;
    }

    // Reset statistics (called when streaming starts)
    void reset_stats() {
        samples_produced = 0;
        samples_dropped = 0;
        i2c_error = false;
    }
};

} // namespace core

#endif // DEVICE_CORE_SHARED_CONTEXT_HPP
