/**
 * Copyright (c) 2021 Raspberry Pi (Trading) Ltd.
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * Adapted from pico-examples/pio/i2c for powermonitor.
 */
#ifndef _PIO_I2C_H
#define _PIO_I2C_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include "hardware/pio.h"
#include "i2c.pio.h"  // Auto-generated by CMake from i2c.pio

#ifdef __cplusplus
extern "C" {
#endif

// Low-level primitives
void pio_i2c_start(PIO pio, uint sm);
void pio_i2c_stop(PIO pio, uint sm);
void pio_i2c_repstart(PIO pio, uint sm);

bool pio_i2c_check_error(PIO pio, uint sm);
void pio_i2c_resume_after_error(PIO pio, uint sm);

void pio_i2c_put_or_err(PIO pio, uint sm, uint16_t data);
uint8_t pio_i2c_get(PIO pio, uint sm);

// Transaction-level API (blocking, like hardware i2c_*_blocking)
// nostop=true emits a repeated-start instead of STOP at the end.
int pio_i2c_write_blocking(PIO pio, uint sm, uint8_t addr,
                           uint8_t *txbuf, uint len, bool nostop);
int pio_i2c_read_blocking(PIO pio, uint sm, uint8_t addr,
                          uint8_t *rxbuf, uint len);

// Convenience: write register pointer (with repeat-start), then read data.
bool pio_i2c_read_reg(PIO pio, uint sm, uint8_t dev_addr,
                      uint8_t reg, uint8_t *buf, size_t len);

#ifdef __cplusplus
}
#endif

#endif // _PIO_I2C_H
